### ISSUE TITLE
Gas savings only applies for first mint

### ISSUE THREAD

**Issue by zkSoju** [kadenzipfel/ERC721K#1]
A majority of the gas savings only applies on the first mint because of SSTORE costing more for setting a storage slot from 0 to non-0.

https://github.com/kadenzipfel/ERC721K/blob/aea8c6b476d334f8d7f1ce2d85507d31c2888460/src/ERC721K.sol#L387

Adding the following to each setUp() test will result in similar gas usage to ERC721A:
`token.mint(address(0xBEEF), 1, "", false);` 

Small savings from short circuiting and interface checking still apply though.

<img width="636" alt="26724a1643e99a4e50ea2be186fdca29" src="https://user-images.githubusercontent.com/28630104/162676951-6b0ae068-db63-4d85-940c-0147c1e0a266.png">

**Comment by kadenzipfel** [comment]
yep, you're right. readme has been updated
